# Name of workflow
name: My First Workflow

# Whem it run
on: [push]

# ToDo
jobs:                        # Name of jobs
  say-hello:                 
    runs-on: ubuntu-latest   # Name of server for run
    
    steps:                   # Step todo
      - name: Say Hi
        run: echo "Hello, Workd! This is my first action."
        
      - name: Check Python Version
        run: python --version