name: exercise5

on:
  push:
    branches: [ "main" ]


jobs:
  exercise5:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Git
        uses: actions/checkout@v4
      
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Run Script
        run: python validate_all.py